name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # A cada 10 minutos

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service
        run: curl https://rd-station-api.onrender.com/health
